export const cars = [
  {
    id: 1,
    slug: "mustang-gt-2025",
    brand: "Ford",
    model: "Mustang GT V8",
    year: "2025",
    body: "Esportivo",
    km: "7000 km",
    price: "R$ 519.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Gasolina",
    color: "Branco",
    power: "488 cv",
    description: "Um clássico reinventado — o Mustang GT 2025 entrega potência visceral com seu V8 aspirado, design agressivo e tecnologia moderna, sendo a perfeita união entre herança americana e performance contemporânea.",
    features: [
      "Motor V8 coyote 5.0 aspirado",
      "Volante esportivo com paddle shift",
      "Suspensão adaptativa MagneRide",
      "Freios Brembo de alta performance",
      "Drift Brake eletrônico",
      "Modos de condução: Normal, Sport, Track, Drag",
      "Rodas aro 19' exclusivas",
      "Sistema de som premium Bang & Olufsen",
      "Sistema de escapamento com válvula ativa",
      "Piloto automático adaptativo",
      "Assistente de permanência em faixa",
      "Frenagem autônoma de emergência",
      "Monitor de ponto cego",
      "Alertaa de tráfego cruzado",
      "Sensores 360° + câmera de ré",
      "Multimídia de 13,2' touchscreen",
    ],

    images: [
      "https://i.postimg.cc/tgBPg1th/mustang_gt1.jpg",
      "https://i.postimg.cc/q71n7tXs/mustang_gt2.jpg",
      "https://i.postimg.cc/Zqw3q9Fc/mustang_gt3.jpg",
      "https://i.postimg.cc/BvSHs5DX/mustang_gt4.jpg",
      "https://i.postimg.cc/25khmdv6/mustang_gt5.jpg",
      "https://i.postimg.cc/hGDTg8xh/mustang_gt6.jpg",
      "https://i.postimg.cc/pdWzxQ8r/mustang_gt7.jpg",
      "https://i.postimg.cc/CKcDKZHK/mustang_gt8.jpg",
      "https://i.postimg.cc/QMf5MBkH/mustang_gt11.jpg",
      "https://i.postimg.cc/43Wt3Kb9/mustang_gt12.jpg",
      "https://i.postimg.cc/0NVmN6dj/mustang_gt9.jpg",
      "https://i.postimg.cc/5tsvtHqj/mustang_gt10.jpg",
      "https://i.postimg.cc/jjMNjWQN/mustang_gt13.jpg",
    ],
  },
  {
    id: 2,
    slug: "hyundai-creta-2020",
    brand: "Hyundai",
    model: "Creta 1.6 Flex",
    year: "2020",
    body: "SUV",
    km: "65.0000 km",
    price: "R$ 92.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Flex",
    color: "Marrom Claro Metálico",
    power: "130 cv",
    description: "Um SUV que equilibra sofisticação e versatilidade — o Creta oferece design imponente, posição de dirigir elevada e tecnologia pensada para transformar cada trajeto em conforto e segurança.",
    features: [
      "Faróis de neblina",
      "Ar condicionado automático digital ",
      "Sensores de estacionamento traseiro ",
      "Direção elétrica progressiva ",
      "Computador de bordo",
      "Airbag frontal duplo",
      "Assistente de partida em rampa (HAC)",
      "Alarme perimétrico",
      "Monitor de pressão dos pneus (TPMS)",
      "Rodas de liga leve 17” diamantadas",
      "Volante revestido em couro, com comandos de piloto automático e áudio",
    ],

    images: [
      "https://i.postimg.cc/qMMHg8Wb/hyundai_creta_1.jpg",
      "https://i.postimg.cc/Hss1jQFv/hyundai_creta_2.jpg",
      "https://i.postimg.cc/kXXPDxkC/hyundai_creta_3.jpg",
      "https://i.postimg.cc/Ghhn9kZb/hyundai_creta_4.jpg",
      "https://i.postimg.cc/RVVxqcjM/hyundai_creta_5.jpg",
      "https://i.postimg.cc/CLLpdj9N/hyundai_creta_6.jpg",
      "https://i.postimg.cc/fTTQkx1B/hyundai_creta_7.jpg",
    ],
  },
  {
    id: 3,
    slug: "hyundai-hb20-2013",
    brand: "Hyundai",
    model: "HB20 1.0 Comfort",
    year: "2013",
    body: "Hatch",
    km: "171.000 km",
    price: "R$ 42.900,00",
    imagePosition: "center 30%",
    transmission: "Manual",
    fuel: "Flex",
    color: "Branco",
    power: "80 cv",
    description: "Compacto, moderno e eficiente — o HB20 Comfort Hatch entrega economia inteligente com design atualizado e conforto na medida certa para o dia a dia urbano.",
    features: [
      "Airbag",
      "Ar Condicionado",
      "Direção Hidráulica",
      "Vidros elétricos traseiros e dianteiros",
      "Radio com USB",
      "Limpador Traseiro",
    ],

    images: [
      "https://i.postimg.cc/RhN0DBhh/hb20_1.jpg",
      "https://i.postimg.cc/0Nn25QJk/hb20_2.jpg",
      "https://i.postimg.cc/qRZJn5LD/hb20_3.jpg",
      "https://i.postimg.cc/hvzS01Zz/hb20_4.jpg",
      "https://i.postimg.cc/WzBsYqxf/hb20_5.jpg",
      "https://i.postimg.cc/FF8FHw1R/hb20_6.jpg",
      "https://i.postimg.cc/hPmDzM7d/hb20_7.jpg",
      "https://i.postimg.cc/15FmnMNb/hb20_8.jpg",
      "https://i.postimg.cc/BncJN6pt/hb20_9.jpg",
    ],
  },
  {
    id: 4,
    slug: "hyundai-hb20-2013",
    brand: "Hyundai",
    model: "HB20 1.0 Comfort Plus",
    year: "2013",
    body: "Sedan",
    km: "117.000 km",
    price: "R$ 49.900,00",
    imagePosition: "center 30%",
    transmission: "Manual",
    fuel: "Flex",
    color: "Marrom",
    power: "80 cv",
    description: "Mais equipado e sofisticado, o HB20 Comfort Plus combina tecnologia, conectividade e economia, elevando a experiência de condução com praticidade e estilo.",
    features: [
      "Airbags frontais (motorista e passageiro)",
      "Freios ABS com EBD",
      "Cintos de segurança de 3 pontos",
      "Encostos de cabeça para todos os ocupantes",
      "ISOFIX para cadeiras infantis",
      "Ar-condicionado manual",
      "Direção hidráulica",
      "Vidros elétricos dianteiros e traseiros",
      "Travas elétricas",
      "Banco do motorista com ajuste de altura",
      "Coluna de direção com regulagem de altura",
      "Desembaçador do vidro traseiro",
      "Abertura interna do porta-malas e do tanque",
      "Computador de bordo",
      "Sistema de som original",
      "Conexão USB",
      "Entrada auxiliar",
      "Rádio AM/FM",
    ],

    images: [
      "https://i.postimg.cc/d1QP5j31/hb20s_1.jpg",
      "https://i.postimg.cc/tTRQBNJ7/hb20s_2.jpg",
      "https://i.postimg.cc/C1MTcs5z/hb20s_3.jpg",
      "https://i.postimg.cc/zBDZxFvv/hb20s_4.jpg",
      "https://i.postimg.cc/XJ2MmBBn/hb20s_5.jpg",
      "https://i.postimg.cc/B6hWkPPq/hb20s_6.jpg",
      "https://i.postimg.cc/FRPt8kkF/hb20s_7.jpg",
    ],
  },
  {
    id: 5,
    slug: "jeep-compass-2018",
    brand: "Jeep",
    model: "Compass Longitude",
    year: "2018",
    body: "SUV",
    km: "82.000 km",
    price: "R$ 84.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Flex",
    color: "Branco",
    power: "166 cv",
    description: "Elegância e presença em um SUV premium — o Compass Longitude une acabamento refinado, tecnologia embarcada e a robustez característica da Jeep para qualquer jornada.",
    features: [
      "Central multimídia com tela sensível ao toque",
      "Ar-condicionado",
      "Computador de bordo",
      "Volante com ajuste de altura",
      "Bancos revestidos em couro (em alguns modelos/fabricantes listam couro ou premium)",
      "Retrovisores externos com rebatimento elétrico (inclusão da linha 2019)",
      "Motor 2.0 Flex com câmbio automático de 6 marchas (tração 4×2)",
      "Faróis de neblina",
      "Direção elétrica assistida",
      "Rodas de liga leve aro 18″ (novo desenho na linha 2019",

    ],

    images: [
      "https://i.postimg.cc/B6Fkx1Z5/jeep_compass_(5).jpg",
      "https://i.postimg.cc/0QSFpJ5j/jeep_compass_(2).jpg",
      "https://i.postimg.cc/d1Cp8TQy/jeep_compass_(3).jpg",
      "https://i.postimg.cc/KzTwngc4/jeep_compass_(1).jpg",
      "https://i.postimg.cc/bJnWQ2YQ/jeep_compass_(4).jpg",
      "https://i.postimg.cc/tT6whVRs/jeep_compass_(1).jpg",
      "https://i.postimg.cc/d1Cp8TQC/jeep_compass_(2).jpg",
      "https://i.postimg.cc/wvNZhsxD/jeep_compass_(3).jpg",
      "https://i.postimg.cc/tT6whVR3/jeep_compass_(4).jpg",
      "https://i.postimg.cc/j5fmzJqQ/jeep_compass_(6).jpg",
      "https://i.postimg.cc/d1Cp8TQ1/jeep_compass_(7).jpg",
    ],
  },
  {
    id: 6,
    slug: "toyota-corolla-2023",
    brand: "Toyota",
    model: "Corolla VVT-IE Flex",
    year: "2023",
    body: "Sedan",
    km: "14.000 km",
    price: "R$ 124.900,00",
    imagePosition: "center 30%",
    transmission: "CVT",
    fuel: "Flex",
    color: "Branco",
    power: "169 cv",
    description: "Referência em sofisticação e confiabilidade, o Corolla 2.0 oferece desempenho suave, tecnologia avançada e um nível de conforto que transforma cada trajeto em uma experiência superior.",
    features: [
      "Painel TFT",
      "Câmbio automático CVT",
      "Rodas de liga leve de 17”",
      "Sensores de estacionamento dianteiro e traseiro ",
      "Câmera de ré com projeção na central multimídia ",
      "Controle eletrônico de estabilidade ",
      "Assistência de partida em rampa",
      "Ar-condicionado digital e automático",
      "Volante multifuncional ",
      "Indicadores de mudança de marcha (Paddle shifts) no volante ",
      "Farois de neblina dianteiro em LED",
      "Sistema de audio com conectividade Bluetooth e entrada USB",
    ],

    images: [
      "https://i.postimg.cc/VkHVpFd0/toyota_corolla_(9).jpg",
      "https://i.postimg.cc/9fRnhq7G/toyota_corolla_(8).jpg",
      "https://i.postimg.cc/cJgbS8n8/toyota_corolla_(7).jpg",
      "https://i.postimg.cc/dVSxp9LR/toyota_corolla_(6).jpg",
      "https://i.postimg.cc/wjbGZk7k/toyota_corolla_(5).jpg",
      "https://i.postimg.cc/52kRTm6B/toyota_corolla_(4).jpg",
      "https://i.postimg.cc/P5FR9MPL/toyota_corolla_(3).jpg",
      "https://i.postimg.cc/Jzd2vQGs/toyota_corolla_(2).jpg",
      "https://i.postimg.cc/DwYMHc8J/toyota_corolla_(1).jpg",
    ],
  },
  {
    id: 7,
    slug: "bmw-320i-2024",
    brand: "BMW",
    model: "320i M Sport 2.0 Turbo",
    year: "2024",
    body: "Sedan",
    km: "10.000 km",
    price: "R$ 309.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Flex",
    color: "Azul Portmão",
    power: "184 cv",
    description: "Esportividade e sofisticação em perfeita harmonia — a 320i M Sport entrega desempenho preciso, design marcante e tecnologia de ponta, proporcionando uma condução dinâmica com o padrão premium da BMW.",
    features: [
      "Motor 2.0 TwinPower Turbo",
      "Ar-condicionado digital de 3 zonas",
      "Volante esportivo M em couro",
      "Câmera 360° com visão ampliada",
      "Faróis Full LED adaptativos",
      "Kit aerodinâmico M (parachoques exclusivos)",
      "Rodas M aro 19”",
      "BMW Live Cockpit Professional (painel digital + multimídia curva)",
      "Volante multifuncional ",
      "Bancos esportivos em couro com ajuste elétrico e memória",
      "Piloto automático adaptativo",
    ],

    images: [
      "https://i.postimg.cc/y6fVJfBq/320i_1.jpg",
      "https://i.postimg.cc/nVdHsdZf/320i_2.jpg",
      "https://i.postimg.cc/y6fVJfBz/320i_3.jpg",
      "https://i.postimg.cc/G3McBMrR/320i_4.jpg",
      "https://i.postimg.cc/zXVqTnDQ/320i_5.jpg",
      "https://i.postimg.cc/MKvz1yZ4/320i_6.jpg",
      "https://i.postimg.cc/9FrcyGXK/320i_7.jpg",
      "https://i.postimg.cc/h4CSJCn2/320i_8.jpg",
      "https://i.postimg.cc/ZYfT9fmf/320i_9.jpg",
      "https://i.postimg.cc/L4yHqySQ/320i_10.jpg",
      "https://i.postimg.cc/XN2VZ2WH/320i_11.jpg"
    ],
  },
  {
    id: 8,
    slug: "chevrolet-montana-2023",
    brand: "Chevrolet",
    model: "Montana Premier",
    year: "2023",
    body: "Pickup",
    km: "37.000 km",
    price: "R$ 119.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Flex",
    color: "Prata Shark",
    power: "133 cv",
    description: "",
    features: [
      "Câmbio automático de 6 marchas",
      "Ar-condicionado digital automático",
      "Bancos em couro",
      "Banco do motorista com ajuste de altura",
      "Volante multifuncional com regulagem de altura e profundidade",
      "Vidros elétricos nas 4 portas",
      "Chave presencial + partida por botão",
      "Apoio de braço para motorista",
      "Faróis Full LED com acendimento automático",
      "DRL em LED",
      "Rodas de liga leve aro 17”",
      "Rack de teto",
      "Retrovisores elétrico"
    ],

    images: [
      "https://i.postimg.cc/kG8mM5H4/montana_premier1.jpg",
      "https://i.postimg.cc/d3dYQ0fD/montana_premier2.jpg",
      "https://i.postimg.cc/qqnTB7Fq/montana_premie3.jpg",
      "https://i.postimg.cc/44hZQ8xc/montana_premier4.jpg",
      "https://i.postimg.cc/DfbFPCwg/montana_premier5.jpg",
      "https://i.postimg.cc/nVQZGdh2/montana_premier6.jpg",
      "https://i.postimg.cc/Pf8hQ65K/montana_premier7.jpg",
      "https://i.postimg.cc/G3srxMm5/montana_premier8.jpg",
      "https://i.postimg.cc/Vsb1W7k2/montana_premier9.jpg"
    ],
  },
  {
    id: 9,
    slug: "chevrolet-celta-2015",
    brand: "Chevrolet",
    model: "Celta Spirit LT",
    year: "2015",
    body: "Hatch",
    km: "183.000 km",
    price: "32.900,00",
    imagePosition: "center 30%",
    transmission: "Manual",
    fuel: "Flex",
    color: "Preto Brilhante",
    power: "78 cv",
    description: " ",
    features: [
      "Câmbio manual de 5 marchas",
      "Rodas aro 17”",
      "Volante esportivo M em couro",
      "Ar-condicionado",
      "Direção hidráulica",
      "Vidros elétricos dianteiros",
      "Travas elétricas",
      "Desembaçador traseiro",
      "Preparação para som"
    ],

    images: [
      "https://i.postimg.cc/KYqFJwLx/celta1.jpg",
      "https://i.postimg.cc/TP7GCFmG/celta2.jpg",
      "https://i.postimg.cc/zByNM7w9/celta3.jpg",
      "https://i.postimg.cc/V6JwTgBy/celta4.jpg",
      "https://i.postimg.cc/PxCHcyzs/celta5.jpg",
      "https://i.postimg.cc/rpncQ3W6/celta6.jpg",
      "https://i.postimg.cc/yNQBvt94/celta7.jpg"
    ],
  },
  {
    id: 10,
    slug: "bmw-x1-2017",
    brand: "BMW",
    model: "X1 Activeflex Sdrive20i",
    year: "2017",
    body: "SUV",
    km: "79.000 km",
    price: "R$ 106.900,00",
    imagePosition: "center 30%",
    transmission: "Automática",
    fuel: "Flex",
    color: "Preto Safira",
    power: "192 cv",
    description: " ",
    features: [
      "Motor 2.0 TwinPower Turbo",
      "Câmbio automático de 8 marchas ",
      "Teto solar panorâmico",
      "Interno claro",
      "Ar-condicionado digital dual zone",
      "Bancos em couro com ajustes elétricos e memória",
      "Central multimídia com espelhamento (Apple CarPlay)",
      "Faróis full LED",
      "Sensor de chuva e crepuscular",
      "Start/Stop",
      "Freio de estacionamento eletrônico",
      "Airbags frontais, laterais e de cortina",
      "ABS + EBD",
      "Controle de estabilidade e tração",
      "Assistente de partida em rampa",
      "Sensores de estacionamento"
    ],

    images: [
      "https://i.postimg.cc/c1Vxppz6/bmw_x1_1.jpg",
      "https://i.postimg.cc/3Jm8YLMh/bmw_x1_2.jpg",
      "https://i.postimg.cc/X7dj42M4/bmw_x1_3.jpg",
      "https://i.postimg.cc/J4ZrMTw1/bmw_x1_4.jpg",
      "https://i.postimg.cc/zXKz8dmG/bmw_x1_5.jpg",
      "https://i.postimg.cc/PrYXT6Gx/bmw_x1_6.jpg",
      "https://i.postimg.cc/BQHS4hWt/bmw_x1_7.jpg",
      "https://i.postimg.cc/3Jm8YLMD/bmw_x1_8.jpg",
      "https://i.postimg.cc/J4ZrMTwX/bmw_x1_9.jpg",
      "https://i.postimg.cc/qB9JPPFR/bmw_x1_10.jpg"
    ],
  },
];
